## importing and loading the data

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px

In [ ]:
df = pd.read_csv('googleplaystore.csv')

## viewing the data

In [ ]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [ ]:
df.describe(include = 'all')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.describe(include = 'object')

,App,Category,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,596,1695,1579,10039,10040,8714,842,326,1459,2451

## checking missing values

In [ ]:
df.isna().sum()

                Missing percentage
Rating                       13.60
Current Ver                   0.07
Android Ver                   0.03
Content Rating                0.01
Type                          0.01
Size                          0.00
Reviews                       0.00
Category                      0.00
App                           0.00
Price                         0.00
Installs                      0.00
Last Updated                  0.00
Genres                        0.00

#### Missing values percentage

In [ ]:
df.isna().mean()*100

## checking duplicates

In [ ]:
df.duplicated().sum()

np.int64(483)

In [ ]:
df[df.duplicated()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,Varies with device,"10,000,000+",Free,0,Everyone,Productivity,"April 6, 2018",Varies with device,Varies with device
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,Varies with device,"1,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,Varies with device,"100,000,000+",Free,0,Everyone,Productivity,"June 27, 2018",Varies with device,Varies with device
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86M,"10,000+",Free,0,Everyone,Medical,"June 1, 2018",0.6.88,5.0 and up
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

### Checking duplicated apps

In [ ]:
df['App'].duplicated().sum()

np.int64(1181)

## checking out of range values

In [ ]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

#### the max rating value should be 5.0

In [ ]:
df['Rating'].describe()

count    9367.000000
mean        4.193338
std         0.537431
min         1.000000
25%         4.000000
50%         4.300000
75%         4.500000
max        19.000000
Name: Rating, dtype: float64

In [ ]:
df['Rating'].value_counts()

Rating
4.4     1109
4.3     1076
4.5     1038
4.2      952
4.6      823
4.1      708
4.0      568
4.7      499
3.9      386
3.8      303
5.0      274
3.7      239
4.8      234
3.6      174
3.5      163
3.4      128
3.3      102
4.9       87
3.0       83
3.1       69
3.2       64
2.9       45
2.8       42
2.6       25
2.7       25
2.5       21
2.3       20
2.4       19
1.0       16
2.2       14
1.9       13
2.0       12
1.7        8
1.8        8
2.1        8
1.6        4
1.4        3
1.5        3
1.2        1
19.0       1
Name: count, dtype: int64

## inspecting columns

In [ ]:
df['Installs'].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0', 'Free'], dtype=object)

In [ ]:
df['Installs'].value_counts()

Installs
1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             907
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
0                    1
Free                 1
Name: count, dtype: int64

In [ ]:
df['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', 'Everyone', '$1.20', '$1.04'], dtype=object)

In [ ]:
df['Price'].value_counts()

Price
0           10040
$0.99         148
$2.99         129
$1.99          73
$4.99          72
            ...
$394.99         1
$1.26           1
Everyone        1
$1.20           1
$1.04           1
Name: count, Length: 93, dtype: int64

In [ ]:
df['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '1,000+',
       '470k', '226k', '240k', '89k', '234k', '257k', '861k', '467k',
       '157k', '44k', '676k', '67k', '552k', '885k', '1020k', '582k',
       '619k'], dtype=object)

In [ ]:
df['Size'].value_counts()

Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
552k                     1
885k                     1
1020k                    1
582k                     1
619k                     1
Name: count, Length: 462, dtype: int64

In [ ]:
df['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [ ]:
df['Category'].value_counts()

Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: count, dtype: int64

In [ ]:
df['Type'].value_counts()

Type
Free    10039
Paid      800
0           1
Name: count, dtype: int64

In [ ]:
df['Content Rating'].value_counts()

Content Rating
Everyone           8714
Teen               1208
Mature 17+          499
Everyone 10+        414
Adults only 18+       3
Unrated               2
Name: count, dtype: int64

# Cleaning the data

In [ ]:
#viewing the corrupted row
df[df['Category'] == '1.9']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

#### Dropping the corrupted row (turns out all corrupted data are in one row)

In [ ]:
# removing corrupted Category value
df = df[df['Category'] != '1.9'].copy()

#### Handling duplicates

##### 1. Dropping identical duplicates

In [ ]:
df = df.drop_duplicates()

##### 2. Handling duplicated apps

In [ ]:
# we keep the row with the highest reviews count
df = df.sort_values('Reviews', ascending= False)

df = df.drop_duplicates(subset='App', keep='first')

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,GollerCepte Live Score,SPORTS,4.2,9992,31M,"1,000,000+",Free,0,Everyone,Sports,"May 23, 2018",6.5,4.1 and up
1,Ad Block REMOVER - NEED ROOT,TOOLS,3.3,999,91k,"100,000+",Free,0,Everyone,Tools,"December 17, 2013",3.2,2.2 and up
2,SnipSnap Coupon App,SHOPPING,4.2,9975,18M,"1,000,000+",Free,0,Everyone,Shopping,"January 22, 2018",1.4,4.3 and up
3,US Open Tennis Championships 2018,SPORTS,4.0,9971,33M,"1,000,000+",Free,0,Everyone,Sports,"June 5, 2018",7.1,5.0 and up
4,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22M,"500,000+",Free,0,Teen,Travel & Local,"August 6, 2018",1.28.1,5.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9654,Curso Básico y Avanzado la Fe de Jesús Audio-T...,FAMILY,NaN,0,11M,10+,Free,0,Everyone 10+,Education,"July 12, 2018",1.0,4.0 and up
9655,CT Pulmonary Angiography,MEDICAL,NaN,0,4.9M,100+,Free,0,Everyone,Medical,"March 24, 2018",1.0,4.0 and up
9656,Theme For Galaxy Note FE,PERSONALIZATION,NaN,0,7.5M,100+,Free,0,Everyone,Personalization,"April 19, 2018",1.1,4.1 and up
9657,Toronto Dating,DATING,NaN,0,14M,100+,Free,0,Mature 17+,Dating,"July 12, 2018",1.0,4.1 and up
9658,PlayMotiv dn edition,BUSINESS,NaN,0,28M,500+,Free,0,Everyone,Business,"April 8, 2018",1.0.2,4.1 and up

#### Converting installs to numeric

In [ ]:
df['Installs'] = df['Installs'].str.replace('+','').str.replace(',','').astype(int)

#### Coverting reviews to numeric

In [ ]:
df['Reviews'] = df['Reviews'].astype(int)

#### Converting price to numeric

In [ ]:
df['Price'] = df['Price'].str.replace('$','').astype(float)

#### Converting size to numeric (in MB)

In [ ]:
def convert_size_to_mb(value):
    """Convert a single Size value to a float in MB."""
    if value == 'Varies with device':
        return np.nan
    if value.endswith('M'):
        return float(value[:-1])
    if value.endswith('k'):
        return float(value[:-1]) / 1024
    return np.nan

In [ ]:
df['Size'] = df['Size'].apply(convert_size_to_mb)

In [ ]:
df['Size'] = df['Size'].round(3)
df['Size']

0       31.000
1        0.089
2       18.000
3       33.000
4       22.000
         ...
9654    11.000
9655     4.900
9656     7.500
9657    14.000
9658    28.000
Name: Size, Length: 9659, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9659 non-null   object
 1   Category        9659 non-null   object
 2   Rating          8196 non-null   float64
 3   Reviews         9659 non-null   int64
 4   Size            8432 non-null   float64
 5   Installs        9659 non-null   int64
 6   Type            9658 non-null   object
 7   Price           9659 non-null   float64
 8   Content Rating  9659 non-null   object
 9   Genres          9659 non-null   object
 10  Last Updated    9659 non-null   object
 11  Current Ver     9651 non-null   object
 12  Android Ver     9657 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 981.1+ KB

In [ ]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,GollerCepte Live Score,SPORTS,4.2,9992,31.000,1000000,Free,0.0,Everyone,Sports,"May 23, 2018",6.5,4.1 and up
1,Ad Block REMOVER - NEED ROOT,TOOLS,3.3,999,0.089,100000,Free,0.0,Everyone,Tools,"December 17, 2013",3.2,2.2 and up
2,SnipSnap Coupon App,SHOPPING,4.2,9975,18.000,1000000,Free,0.0,Everyone,Shopping,"January 22, 2018",1.4,4.3 and up
3,US Open Tennis Championships 2018,SPORTS,4.0,9971,33.000,1000000,Free,0.0,Everyone,Sports,"June 5, 2018",7.1,5.0 and up
4,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.000,500000,Free,0.0,Teen,Travel & Local,"August 6, 2018",1.28.1,5.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9654,Curso Básico y Avanzado la Fe de Jesús Audio-T...,FAMILY,NaN,0,11.000,10,Free,0.0,Everyone 10+,Education,"July 12, 2018",1.0,4.0 and up
9655,CT Pulmonary Angiography,MEDICAL,NaN,0,4.900,100,Free,0.0,Everyone,Medical,"March 24, 2018",1.0,4.0 and up
9656,Theme For Galaxy Note FE,PERSONALIZATION,NaN,0,7.500,100,Free,0.0,Everyone,Personalization,"April 19, 2018",1.1,4.1 and up
9657,Toronto Dating,DATING,NaN,0,14.000,100,Free,0.0,Mature 17+,Dating,"July 12, 2018",1.0,4.1 and up
9658,PlayMotiv dn edition,BUSINESS,NaN,0,28.000,500,Free,0.0,Everyone,Business,"April 8, 2018",1.0.2,4.1 and up

# Handling missing values

In [ ]:
df.isna().mean()*100

App                0.000000
Category           0.000000
Rating            15.146495
Reviews            0.000000
Size              12.703178
Installs           0.000000
Type               0.010353
Price              0.000000
Content Rating     0.000000
Genres             0.000000
Last Updated       0.000000
Current Ver        0.082824
Android Ver        0.020706
dtype: float64

#### dropping missing values rows for 'Current Ver' and 'Android Ver' and 'Type' columns (missing values percentages too low)

In [ ]:
df = df.dropna(subset=['Current Ver', 'Android Ver', 'Type'], ignore_index=True) 
df.isna().mean()*100

App                0.000000
Category           0.000000
Rating            15.111940
Reviews            0.000000
Size              12.707297
Installs           0.000000
Type               0.000000
Price              0.000000
Content Rating     0.000000
Genres             0.000000
Last Updated       0.000000
Current Ver        0.000000
Android Ver        0.000000
dtype: float64

#### to fix pandas SettingWithCopyWarning, we create a copy of the DataFrame before filling missing values

In [ ]:
df = df.copy()

#### filling missing values for 'Rating' column with the median value of ratings for each category

In [ ]:
df['Rating'] = df.groupby('Category')['Rating'].transform(lambda r: r.fillna(r.median()))

In [ ]:
df.isna().mean()*100

App                0.000000
Category           0.000000
Rating             0.000000
Reviews            0.000000
Size              12.707297
Installs           0.000000
Type               0.000000
Price              0.000000
Content Rating     0.000000
Genres             0.000000
Last Updated       0.000000
Current Ver        0.000000
Android Ver        0.000000
dtype: float64

#### missing values for 'Size' column won't be filled as it was 'Varies with device' so we add a new column 'size_varies' to indicate if the size varies with device or not

In [ ]:
df['size_varies'] = df['Size'].isna()
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,size_varies
0,GollerCepte Live Score,SPORTS,4.2,9992,31.000,1000000,Free,0.0,Everyone,Sports,"May 23, 2018",6.5,4.1 and up,False
1,Ad Block REMOVER - NEED ROOT,TOOLS,3.3,999,0.089,100000,Free,0.0,Everyone,Tools,"December 17, 2013",3.2,2.2 and up,False
2,SnipSnap Coupon App,SHOPPING,4.2,9975,18.000,1000000,Free,0.0,Everyone,Shopping,"January 22, 2018",1.4,4.3 and up,False
3,US Open Tennis Championships 2018,SPORTS,4.0,9971,33.000,1000000,Free,0.0,Everyone,Sports,"June 5, 2018",7.1,5.0 and up,False
4,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.000,500000,Free,0.0,Teen,Travel & Local,"August 6, 2018",1.28.1,5.0 and up,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,Curso Básico y Avanzado la Fe de Jesús Audio-T...,FAMILY,4.3,0,11.000,10,Free,0.0,Everyone 10+,Education,"July 12, 2018",1.0,4.0 and up,False
9644,CT Pulmonary Angiography,MEDICAL,4.3,0,4.900,100,Free,0.0,Everyone,Medical,"March 24, 2018",1.0,4.0 and up,False
9645,Theme For Galaxy Note FE,PERSONALIZATION,4.4,0,7.500,100,Free,0.0,Everyone,Personalization,"April 19, 2018",1.1,4.1 and up,False
9646,Toronto Dating,DATING,4.1,0,14.000,100,Free,0.0,Mature 17+,Dating,"July 12, 2018",1.0,4.1 and up,False
9647,PlayMotiv dn edition,BUSINESS,4.2,0,28.000,500,Free,0.0,Everyone,Business,"April 8, 2018",1.0.2,4.1 and up,False

In [ ]:
df['size_varies'].value_counts()

size_varies
False    8422
True     1226
Name: count, dtype: int64

#### Converting 'Last Updated' to date time

In [ ]:
df['Last Updated'] = pd.to_datetime(df['Last Updated'])

In [ ]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,size_varies
0,GollerCepte Live Score,SPORTS,4.2,9992,31.000,1000000,Free,0.0,Everyone,Sports,2018-05-23,6.5,4.1 and up,False
1,Ad Block REMOVER - NEED ROOT,TOOLS,3.3,999,0.089,100000,Free,0.0,Everyone,Tools,2013-12-17,3.2,2.2 and up,False
2,SnipSnap Coupon App,SHOPPING,4.2,9975,18.000,1000000,Free,0.0,Everyone,Shopping,2018-01-22,1.4,4.3 and up,False
3,US Open Tennis Championships 2018,SPORTS,4.0,9971,33.000,1000000,Free,0.0,Everyone,Sports,2018-06-05,7.1,5.0 and up,False
4,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.000,500000,Free,0.0,Teen,Travel & Local,2018-08-06,1.28.1,5.0 and up,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9643,Curso Básico y Avanzado la Fe de Jesús Audio-T...,FAMILY,4.3,0,11.000,10,Free,0.0,Everyone 10+,Education,2018-07-12,1.0,4.0 and up,False
9644,CT Pulmonary Angiography,MEDICAL,4.3,0,4.900,100,Free,0.0,Everyone,Medical,2018-03-24,1.0,4.0 and up,False
9645,Theme For Galaxy Note FE,PERSONALIZATION,4.4,0,7.500,100,Free,0.0,Everyone,Personalization,2018-04-19,1.1,4.1 and up,False
9646,Toronto Dating,DATING,4.1,0,14.000,100,Free,0.0,Mature 17+,Dating,2018-07-12,1.0,4.1 and up,False
9647,PlayMotiv dn edition,BUSINESS,4.2,0,28.000,500,Free,0.0,Everyone,Business,2018-04-08,1.0.2,4.1 and up,False